### ISSUE TITLE
PathFind Results Error

### ISSUE THREAD

**Issue by marsface** [ripple/ripple-client-desktop#305]
When I try to create payments there were no results for the following values:
Sending USD: Values between 2 and 14 = no results, 1 or >14 worked
Sending BRL: Values between 5 and 54 = no results, < 5 or > 54 worked

EDIT: The values were the result of fulfilling two conditions:
1 - There is a valid path to deliver an IOU using XRP
2 - The amount of XRP used in the payment must be high enough to cause "Error: Exceeding max value of 100000000000\n"

Version: 1.3.2-60-g339e6e1
Im using windows 10 64bits version

**Comment by RafOlP** [comment]
Maybe its just an interface problem, but its quite frustrating.

**Comment by marsface** [comment]
I got this error message in dev version when performing the task above:
`[4017:1130/093532:INFO:CONSOLE(106817)] ""Error: Exceeding max value of 100000000000\n    at Amount._check_limits (http://localhost:3000/js/vendor.js:39000:14)\n    at Amount._set_value (http://localhost:3000/js/vendor.js:38784:9)\n    at Amount._copy (http://localhost:3000/js/vendor.js:39019:9)\n    at Amount.multiply (http://localhost:3000/js/vendor.js:38812:16)\n    at Amount.scale (http://localhost:3000/js/vendor.js:38816:16)\n    at eval (eval at \u003Canonymous\u003E (http://localhost:3000/js/vendor.js:402:6), \u003Canonymous\u003E:26721:42)\n    at arrayMap (http://localhost:3000/js/vendor.js:25296:26)\n    at Function.map (http://localhost:3000/js/vendor.js:30600:15)\n    at eval (eval at \u003Canonymous\u003E (http://localhost:3000/js/vendor.js:402:6), \u003Canonymous\u003E:26704:43)\n    at Scope.$eval (http://localhost:3000/js/vendor.js:110349:29)"", source: http://localhost:3000/js/vendor.js (106817)`

**Comment by marsface** [comment]
ok, it looks like the error is inprocesing the returning results from pathfind, for XRP > IOU payments, generating wrong values for XRP, and this error causes the other paths to be hidden too.
Why are the values being wrongly built? Is it a conflict between ripple-lib's version and rippled's version?

**Comment by jwhelan72** [comment]
I'm having a similar problem with the pathfinding algorithm in the desktop client when trying to send small amounts of BTC to a wallet.  It's really weird.  It finds a path for 0.49 BTC but refuses to find a path for 0.4 BTC.

**Comment by marsface** [comment]
Probably because 0.49 btc returns no paths for xrp > btc, only IOU > btc,
so the xrp limit bug is not triggered.

Em sáb, 16 de jan de 2016 05:07, John Whelan <notifications@github.com>
escreveu:

> I'm having a similar problem with the pathfinding algorithm in the desktop
> client when trying to send small amounts of BTC to a wallet. It's really
> weird. It finds a path for 0.49 BTC but refuses to find a path for 0.4 BTC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ripple/ripple-client-desktop/issues/305#issuecomment-172167616>
> .
>
-- 

Obrigado,
Rafael

*Rafael Olaio - CEO*
tel +55 11 2337.2225
cel +55 11 99522.7572
rippex.net

Esta mensagem pode conter informação confidencial e/ou privilegiada. Se
você não for o destinatário ou a pessoa autorizada a receber esta mensagem,
não poderá usar, copiar ou divulgar as informações nela contidas ou tomar
qualquer ação baseada nessas informações. Se você recebeu esta mensagem por
engano, por favor avise imediatamente o remetente, respondendo o e-mail e
em seguida apague-o.This message may contain confidential and/or privileged
information. If you are not the addressee or authorized to receive this for
the addressee, you must not use, copy, disclose or take any action based on
this message or any information here in. If you have received this message
in error, please advise the sender immediately by reply e-mail and delete
this message.

**Comment by marsface** [comment]
Fixed by
