### ISSUE TITLE
error in nw_shell.cc on startup, spinner spins forever

### ISSUE THREAD

**Issue by leberknecht** [ripple/ripple-client-desktop#325]
Hi! 
I ran `gulp packages` and the executable was created, but on startup i see this error: 
```bash
% ./RippleAdminConsole-1.4.0 
[5923:0510/151605:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[5923:0510/151605:ERROR:nw_shell.cc(336)] SyntaxError: Unexpected token =>
[5923:0510/151605:INFO:CONSOLE(55547)] "Uncaught SyntaxError: Unexpected token =>", source: file:///tmp/.org.chromium.Chromium.GVU73C/js/vendor.js (55547)
[5923:0510/151605:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'fn' of undefined
    at file:///tmp/.org.chromium.Chromium.GVU73C/js/deps-07a4d1f88e.js:1:5686
    at file:///tmp/.org.chromium.Chromium.GVU73C/js/deps-07a4d1f88e.js:1:8216
[5923:0510/151605:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'fn' of undefined", source: file:///tmp/.org.chromium.Chromium.GVU73C/js/deps-07a4d1f88e.js (1)
[5923:0510/151605:ERROR:nw_shell.cc(336)] ReferenceError: $ is not defined
    at file:///tmp/.org.chromium.Chromium.GVU73C/index.html:5:7
[5923:0510/151605:INFO:CONSOLE(5)] "Uncaught ReferenceError: $ is not defined", source: file:///tmp/.org.chromium.Chromium.GVU73C/index.html (5)
[5923:0510/151606:ERROR:nw_shell.cc(336)] ReferenceError: $ is not defined
    at file:///tmp/.org.chromium.Chromium.GVU73C/index.html:10:45
[5923:0510/151606:INFO:CONSOLE(10)] "Uncaught ReferenceError: $ is not defined", source: file:///tmp/.org.chromium.Chromium.GVU73C/index.html (10)
```
A browser is spawned, i see a spinner, but thats it, nothing happens. 

Update: doh, just noticed that i'm running npm 4, will try with 0.12

**Comment by leberknecht** [comment]
Indeed, solved the problem, sorry!
